# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: Lansechen/bs17k_collection_filtered_easy_maxlength32768
dataset_configs:
- all
dataset_train_split: train
dataset_num_proc: 48

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
resume_from_checkpoint: false
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-3B-Instruct-Distill-bs17k-fhm32768-batch32-epoch3-8192
hub_strategy: every_save
learning_rate: 5.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: true
max_length: 8192
max_steps: -1
num_train_epochs: 3
output_dir: data/Qwen2.5-3B-Instruct-Distill-bs17k-fhm32768-batch32-epoch3-8192
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
use_liger: false #true ?loss error
warmup_ratio: 0.05